# Core session settings
session:
  # The amount of time in seconds to update session information
  # Warning: This can be no lower than 20 due to xbox rate limits
  update-interval: 30

  # Should we query the bedrock server to sync the session information
  query-server: true

  # This uses checker.geysermc.org for querying if the native ping fails
  # This can be useful in the case of docker networks or routing problems causing the native ping to fail
  web-query-fallback: false

  # The data to broadcast over xbox live, this is the default if querying is enabled
  session-info:
    host-name: "EARLES"
    world-name: "\u00A7aEARLES"
    version: 1.23.31
    protocol: 527
    players: 3
    max-players: 6
    ip: mc.earles.io
    port: 19132

# Friend/follower list sync settings
friend-sync:
  # The amount of time in seconds to check for follower changes
  # This can be no lower than 20 due to xbox rate limits
  update-interval: 20

  # Should we automatically follow people that follow us
  auto-follow: true

  # Should we automatically unfollow people that no longer follow us
  auto-unfollow: true

# Enable debug logs
debug-log: false

# Suppresses "Updated session!" log into debug
suppress-session-update-info: false