services:
  minecraft:
    image: itzg/minecraft-bedrock-server
    container_name: minecraft
    restart: unless-stopped
    ports:
      - 19132:19132/tcp
      - 19132:19132/udp
    environment:
      # - UID=0
      # - GID=0
      - TZ=US/Denver
      - EULA=true
      - SERVER_NAME=EARLES
      - GAMEMODE=survival
      - FORCE_GAMEMODE=false
      - DIFFICULTY=easy
      - ALLOW_CHEATS=true
      - MAX_PLAYERS=6
      - ONLINE_MODE=true
      # - WHITE_LIST
      # - ALLOW_LIST
      # - SERVER_PORT
      # - SERVER_PORT_V6
      - ENABLE_LAN_VISIBILITY=true
      - VIEW_DISTANCE=128
      # - TICK_DISTANCE
      - PLAYER_IDLE_TIMEOUT=0
      - MAX_THREADS=4
      - LEVEL_NAME=HelloWorld
      # - LEVEL_NAME=1CHUNK
      # - LEVEL_SEED
      # - LEVEL_TYPE
      - DEFAULT_PLAYER_PERMISSION_LEVEL=member
      # - OPS=2533275026015377 #aearles
      - OPS=2533275026015377,2535421067961767,2535407829863530 #aearles, hcearles, ttearles
    volumes:
      - bedrock-data:/data
     # - /mnt/b2/earles-bedrock/worlds:/data/worlds
    networks:
      - backend

  mcxboxbroadcast:
    image: ghcr.io/rtm516/mcxboxbroadcast:latest
    container_name: mcxboxbroadcast
    restart: unless-stopped
    environment:
      # - UID=0
      # - GID=0
      - TZ=US/Denver
    volumes:
      - /mnt/b2/earles-bedrock/MCXboxBroadcastStandalone.jar:/opt/app/MCXboxBroadcastStandalone.jar
      # - ./config.yml:/opt/app/config/config.yml
      - /mnt/b2/earles-bedrock/config:/opt/app/config
    networks:
      - backend

volumes:
  bedrock-data:
  bedrock-config:

networks:
  backend: